[{"lineNumber": 36, "col_offset": 29, "nodeName": "Exception", "type": "Type[Exception]"}, {"lineNumber": 40, "col_offset": 4, "nodeName": "__init__", "type": "Callable[..., Any]"}, {"lineNumber": 47, "col_offset": 37, "nodeName": "Exception", "type": "Type[Exception]"}, {"lineNumber": 42, "col_offset": 8, "nodeName": "in_collision", "type": "Any"}, {"lineNumber": 42, "col_offset": 28, "nodeName": "in_collision", "type": "Any"}, {"lineNumber": 43, "col_offset": 8, "nodeName": "not_confident", "type": "Any"}, {"lineNumber": 43, "col_offset": 29, "nodeName": "not_confident", "type": "Any"}, {"lineNumber": 42, "col_offset": 8, "nodeName": "self", "type": "NoValidGraspsException"}, {"lineNumber": 43, "col_offset": 8, "nodeName": "self", "type": "NoValidGraspsException"}, {"lineNumber": 44, "col_offset": 8, "nodeName": "__init__", "type": "Callable[..., None]"}, {"lineNumber": 44, "col_offset": 27, "nodeName": "self", "type": "NoValidGraspsException"}, {"lineNumber": 44, "col_offset": 8, "nodeName": "Exception", "type": "Type[Exception]"}, {"lineNumber": 44, "col_offset": 34, "nodeName": "args", "type": "Tuple[Any, ...]"}, {"lineNumber": 44, "col_offset": 42, "nodeName": "kwargs", "type": "Dict[str, Any]"}]