[{"lineNumber": 11, "col_offset": 17, "nodeName": "GenericFilesystem", "type": "Type[plugins.generic.filesystem.Filesystem]"}, {"lineNumber": 12, "col_offset": 4, "nodeName": "__init__", "type": "Callable[[Any], Any]"}, {"lineNumber": 15, "col_offset": 4, "nodeName": "readFile", "type": "Callable[[Any, Any], Any]"}, {"lineNumber": 19, "col_offset": 4, "nodeName": "writeFile", "type": "Callable[..., Any]"}, {"lineNumber": 16, "col_offset": 8, "nodeName": "errMsg", "type": "str"}, {"lineNumber": 20, "col_offset": 8, "nodeName": "errMsg", "type": "str"}, {"lineNumber": 13, "col_offset": 8, "nodeName": "__init__", "type": "Callable[[plugins.generic.filesystem.Filesystem], None]"}, {"lineNumber": 13, "col_offset": 35, "nodeName": "self", "type": "Filesystem"}, {"lineNumber": 17, "col_offset": 14, "nodeName": "SqlmapUnsupportedFeatureException", "type": "Type[lib.core.exception.SqlmapUnsupportedFeatureException]"}, {"lineNumber": 17, "col_offset": 48, "nodeName": "errMsg", "type": "str"}, {"lineNumber": 21, "col_offset": 14, "nodeName": "SqlmapUnsupportedFeatureException", "type": "Type[lib.core.exception.SqlmapUnsupportedFeatureException]"}, {"lineNumber": 21, "col_offset": 48, "nodeName": "errMsg", "type": "str"}, {"lineNumber": 13, "col_offset": 8, "nodeName": "GenericFilesystem", "type": "Type[plugins.generic.filesystem.Filesystem]"}]