[{"lineNumber": 1, "col_offset": 17, "nodeName": "Exception", "type": "Type[Exception]"}, {"lineNumber": 8, "col_offset": 20, "nodeName": "CLgenError", "type": "Type[CLgenError]"}, {"lineNumber": 16, "col_offset": 16, "nodeName": "CLgenError", "type": "Type[CLgenError]"}, {"lineNumber": 23, "col_offset": 14, "nodeName": "InternalError", "type": "Type[InternalError]"}, {"lineNumber": 30, "col_offset": 18, "nodeName": "UserError", "type": "Type[UserError]"}]