[{"lineNumber": 17, "col_offset": 32, "nodeName": "ValueError", "type": "Type[ValueError]"}, {"lineNumber": 21, "col_offset": 8, "nodeName": "allowed_statuses", "type": "Any"}, {"lineNumber": 21, "col_offset": 32, "nodeName": "allowed_statuses", "type": "Any"}, {"lineNumber": 22, "col_offset": 8, "nodeName": "actual_status", "type": "Any"}, {"lineNumber": 22, "col_offset": 29, "nodeName": "actual_status", "type": "Any"}, {"lineNumber": 21, "col_offset": 8, "nodeName": "self", "type": "UnexpectedStatusException"}, {"lineNumber": 22, "col_offset": 8, "nodeName": "self", "type": "UnexpectedStatusException"}, {"lineNumber": 23, "col_offset": 8, "nodeName": "__init__", "type": "Callable[..., None]"}, {"lineNumber": 23, "col_offset": 56, "nodeName": "message", "type": "Any"}, {"lineNumber": 23, "col_offset": 8, "nodeName": "super", "type": "Type[super]"}, {"lineNumber": 23, "col_offset": 14, "nodeName": "UnexpectedStatusException", "type": "Type[UnexpectedStatusException]"}, {"lineNumber": 23, "col_offset": 41, "nodeName": "self", "type": "UnexpectedStatusException"}]